title: Dresdner Sprachentreff e.V.
baseURL: 'https://sprachentreff.medien-dresden.de/'
languageCode: de-DE
theme: airspace

disableKinds:
  - RSS

frontmatter:
  lastmod:
    - lastmod
    - ":fileModTime"
    - ":default"

ignoreFiles: [ "static/img/blog.*", "\\.boo$" ]

taxonomies:
  - tag: ""
    group: ""
    category: ""

params:
  
  blog:
    enable: false
    title: Get The Latest On What We're doing
    subtitle: 'Catch up with us, anytime and anywhere'
    
  custom_css: []
  dateFormat: 6. January 2006
  home: Home
