title = "Dresdner Sprachentreff e.V."
baseURL = "https://www.example.com"
languageCode = "en-us"
theme = "airspace"

[menu]

  [[menu.header]]
    weight = 5
    name = "Förderung"
    title = "Förderung durch Bildungsprämie"
    url = "/Förderung"

  [[menu.header]]
    weight = 5
    name = 'Kontakt'
    title = "Ihr Kontakt zu uns"
    url = "/kontakt"

  [[menu.footer]]
    weight = 1
    name = "Impressum"
    url = "/impressum"
    
  [[menu.footer]]
    weight = 2
    name = "Datenschutz"
    url = "/datenschutz"

  [[menu.footer]]
    weight = 3
    name = "Kontakt"
    url = "/kontakt"

# The site's parameters
[params]

  custom_css = []

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "<strong>Dresdner</br>Sprachentreff</strong>"
    subtitle = "Sprachkurse vom Anfänger zum Profi</br>Mit maximal 7 Teilnehmern pro Kurs"

  [params.wrapper]
    enable = true
    title = "Welcome!"
    italic = "Haben Sie sich vorgenommen, Ihre Fremdsprachenkenntnisse zu verbessern? Möchten Sie lernen, sich in anderen Sprachen genauso ungezwungen und ohne Hemmungen auszudrücken wie in Ihrer Muttersprache?"
    paragraph = "Fangen Sie am besten gleich an, Ihre guten Vorsätze in die Tat umzusetzen! Mit unserer Hilfe meistern Sie spielend alle Situationen im Ausland, im Urlaub, auf Dienstreisen."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Lernen Sie Englisch, Spanisch, Französisch, Italienisch oder Tschechisch"
    content = "... vom Anfänger bis zur Profikonversation, zwanglos um den runden Tisch gruppiert, bei Kaffee, Tee und Gebäck. Unsere Kursleiter bringen Ihnen Vokabeln, Grammatik und vor allem 'freies Sprechen' bei, aber es gibt keinen Leistungszwang und wenig Hausaufgaben, denn Sie sollen ja gern zum Sprachtreff e.V. kommen, als Ausgleich zu Ihrem täglichen Stress. Sie erzielen mit Sicherheit gute Lernerfolge, da wir maximal 7 Teilnehmer(innen) pro Kurs aufnehmen."
    [params.feature.button]
      caption = "jetzt anmelden"
      url = "/kontakt/"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
