title: Dresdner Sprachentreff e.V.
baseURL: 'https://sprachentreff.medien-dresden.de/'
languageCode: de-DE
theme: airspace

menu:
  header:
    - weight: 5
      name: Förderung
      title: Förderung durch Bildungsprämie
      url: /Förderung
    - weight: 5
      name: Kontakt
      title: Ihr Kontakt zu uns
      url: /kontakt
  footer:
    - weight: 1
      name: Impressum
      url: /impressum/
    - weight: 2
      name: Datenschutz
      url: /datenschutz/
    - weight: 3
      name: Kontakt
      url: /kontakt/

taxonomies:
  - tag: ""
    group: ""
    category: ""

params:
  
  address:
    short: Wilthener Straße 6a, 01324 Dresden
    long: |
      Dresdner Sprachentreff e.V.  
      Wilthener Straße 6a  
      01324 Dresden  
      Deutschland

  phone: 0351 268 59 86
  email: info@sprachentreff.de

  society:
    register_court: Dresden
    register_number: "000 000"
    tax_number: "0000 0000"
    chairman: |
      Marion Pestel  
      Wilthener Straße 6a  
      01324 Dresden

  custom_css: []
  dateFormat: 6. January 2006
  home: Home
  
  slider:
    enable: true
    title: Dresdner</br>Sprachentreff
    subtitle: Sprachkurse vom Anfänger zum Profi</br>Mit maximal 7 Teilnehmern pro Kurs
    
  wrapper:
    enable: true
    title: Welcome!
    italic: >-
      Haben Sie sich vorgenommen, Ihre Fremdsprachenkenntnisse zu verbessern?
      Möchten Sie lernen, sich in anderen Sprachen genauso ungezwungen und ohne
      Hemmungen auszudrücken wie in Ihrer Muttersprache?
    paragraph: >-
      Fangen Sie am besten gleich an, Ihre guten Vorsätze in die Tat umzusetzen!
      Mit unserer Hilfe meistern Sie spielend alle Situationen im Ausland, im
      Urlaub, auf Dienstreisen.
      
  blog:
    enable: false
    title: Get The Latest On What We're doing
    subtitle: 'Catch up with us, anytime and anywhere'
    
  feature:
    enable: true
    title: 'Lernen Sie Englisch, Spanisch, Französisch, Italienisch oder Tschechisch'
    content: >-
      ... vom Anfänger bis zur Profikonversation, zwanglos um den runden Tisch
      gruppiert, bei Kaffee, Tee und Gebäck. Unsere Kursleiter bringen Ihnen
      Vokabeln, Grammatik und vor allem 'freies Sprechen' bei, aber es gibt
      keinen Leistungszwang und wenig Hausaufgaben, denn Sie sollen ja gern zum
      Sprachtreff e.V. kommen, als Ausgleich zu Ihrem täglichen Stress. Sie
      erzielen mit Sicherheit gute Lernerfolge, da wir maximal 7
      Teilnehmer(innen) pro Kurs aufnehmen.
    button:
      caption: jetzt anmelden
      url: /kontakt/
      
  call:
    enable: true
    title: Bildungsprämie des Bundes
    paragraph: >-
      Mit der Bildungsprämie beteiligt sich die Bundesregierung an den Kosten
      qualifizierter Weiterbildungen, welche Ihrer beruflichen Zukunft
      förderlich sind, z. B. an einer Sprachausbildung Englisch beim Dresdner
      Sprachentreff e. V.
    button:
      text: Infos zur Förderung
      url: /förderung/
      
  contact:
    enable: true
    form:
      name: Ihr Name
      email: Ihre E-Mail Adresse
      subject: Ihr Anliegen
      message: Ihre Nachricht
      button: senden
    box:
      title: Kontaktieren Sie uns ...
    gmaps:
      title: ... und kommen Sie vorbei!
