---
title: Dresdner Sprachentreff e.V.
baseURL: https://sprachentreff.medien-dresden.de/
languageCode: de-DE
theme: airspace
disableKinds:
- RSS
frontmatter:
  lastmod:
  - lastmod
  - ":fileModTime"
  - ":default"
ignoreFiles:
- static/img/blog.*
- "\\.boo$"
taxonomies:
- tag: ''
  group: ''
  category: ''
params:
  blog:
    enable: false
    title: Get The Latest On What We're doing
    subtitle: Catch up with us, anytime and anywhere
  custom_css: []
  dateFormat: 6. January 2006
  home: Home
  address:
    short: Wilthener Straße 6a, 01324 Dresden
    long: "Dresdner Sprachentreff e.V.  \nWilthener Straße 6a  \n01324 Dresden  \nDeutschland\n"
  phone: 0351 268 59 86
  email: info@sprachentreff.de
  society:
    register_court: Dresden
    register_number: VR 3663
    tax_number: 202/140/31656
    chairman: "Marion Pestel  \nWilthener Straße 6a  \n01324 Dresden\n"
  slider:
    enable: true
    title: Dresdner<br>Sprachentreff
    subtitle: Sprachkurse vom Anfänger zum Profi</br>Mit maximal 7 Teilnehmern pro
      Kurs
  wrapper:
    enable: true
    title: Welcome!
    italic: Haben Sie sich vorgenommen, Ihre Fremdsprachenkenntnisse zu verbessern?
      Möchten Sie lernen, sich in anderen Sprachen genauso ungezwungen und ohne Hemmungen
      auszudrücken wie in Ihrer Muttersprache?
    paragraph: Fangen Sie am besten gleich an, Ihre guten Vorsätze in die Tat umzusetzen!
      Mit unserer Hilfe meistern Sie spielend alle Situationen im Ausland, im Urlaub,
      auf Dienstreisen.
  feature:
    enable: true
    title: Lernen Sie Englisch, Spanisch, Französisch, Italienisch oder Tschechisch
    content: "... vom Anfänger bis zur Profikonversation, zwanglos um den runden Tisch
      gruppiert, bei Kaffee, Tee und Gebäck. Unsere Kursleiter bringen Ihnen Vokabeln,
      Grammatik und vor allem 'freies Sprechen' bei, aber es gibt keinen Leistungszwang
      und wenig Hausaufgaben, denn Sie sollen ja gern zum Sprachtreff e.V. kommen,
      als Ausgleich zu Ihrem täglichen Stress. Sie erzielen mit Sicherheit gute Lernerfolge,
      da wir maximal 7 Teilnehmer(innen) pro Kurs aufnehmen."
    button:
      caption: jetzt anmelden
      url: "/kontakt/"
  call:
    enable: true
    title: Bildungsprämie des Bundes
    paragraph: Mit der Bildungsprämie beteiligt sich die Bundesregierung an den Kosten
      qualifizierter Weiterbildungen, welche Ihrer beruflichen Zukunft förderlich
      sind, z. B. an einer Sprachausbildung Englisch beim Dresdner Sprachentreff e.
      V.
    button:
      text: Infos zur Förderung
      url: "/förderung/"
  contact:
    enable: true
    form:
      name: Ihr Name
      email: Ihre E-Mail Adresse
      subject: Ihr Anliegen
      message: Ihre Nachricht
      button: senden
    box:
      title: Kontaktieren Sie uns ...
    gmaps:
      title: "... und kommen Sie vorbei!"
