---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: config.yml
  label: allgemein
  match: "**/*"
- type: directory
  path: data
  label: Startseite
  create: none
  match: "**/*"
- type: directory
  path: content
  label: Unterseiten
  create: none
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
